/*
 * Copyright 2026, Sirius Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Regression test: `WHERE <col> IS NULL` over a parquet scan used to SIGSEGV in
// cuDF's row-group statistics filter, which cannot evaluate a null predicate
// against min/max stats. Sirius now pushes only the null-free conjuncts and
// applies the full predicate post-decode.
//
// The partial-push cases are the delicate ones: when only part of a conjunction
// reaches the reader, the scan must not be reported as fully row-filtered, or
// the dropped null conjuncts are silently never applied.
//
// 6000 rows at ROW_GROUP_SIZE 2048 is deliberate: DuckDB's writer flushes a
// whole buffered DataChunk (<= 2048 rows) as one row group, so a smaller table
// would land in a single row group and barely exercise the stats path.

#include <catch.hpp>
#include <duckdb.hpp>
#include <utils/gpu_execution_fixture.hpp>
#include <utils/parquet_fixture_utils.hpp>

#include <string>
#include <vector>

namespace {

using sirius::test::scoped_sirius_disable;

/// Partially-NULL `v` (and `s`) over several row groups, read via read_parquet.
class ParquetNullPredicateFixture : public sirius::test::GpuExecutionFixture {
 public:
  ParquetNullPredicateFixture()
  {
    auto const pq_path = dir_.file("null_pred.parquet");

    // Generated by a throwaway Sirius-disabled DuckDB so the extension callback
    // never runs during COPY. The guard restores the previous value even if a
    // REQUIRE below throws.
    {
      scoped_sirius_disable disable_guard;
      duckdb::DuckDB gen_db(nullptr);
      duckdb::Connection gen(gen_db);
      for (auto const& sql : std::vector<std::string>{
             "CREATE TABLE np (id INTEGER, v INTEGER, s VARCHAR, flag BOOLEAN,"
             "                 flag_dense BOOLEAN)",
             "INSERT INTO np SELECT i,"
             "  CASE WHEN i % 3 = 0 THEN NULL ELSE i END,"
             "  CASE WHEN i % 4 = 0 THEN NULL ELSE 'r' || CAST(i AS VARCHAR) END,"
             "  CASE WHEN i % 2 = 0 THEN (i % 4 = 0) END,"
             "  (i % 4 = 0)"
             "  FROM range(1, 6001) AS t(i)",
             "COPY np TO '" + pq_path + "' (FORMAT PARQUET, ROW_GROUP_SIZE 2048)",
           }) {
        auto r = gen.Query(sql);
        REQUIRE(r);
        if (r->HasError()) { UNSCOPED_INFO("fixture setup error: " << r->GetError()); }
        REQUIRE_FALSE(r->HasError());
      }
    }

    scan_ = "read_parquet('" + pq_path + "')";
  }

 protected:
  // Cleans itself up; see scratch_dir.
  sirius::test::scratch_dir dir_{"null_pred"};
  std::string scan_;
};

/// Same data, hive-partitioned. The partitioned scan assembles inline in
/// materialize_table and returns ROW_FILTERED_AND_PROJECTED, bypassing
/// post_filter_and_project entirely — so it has its OWN copy of the
/// "did the reader apply the whole predicate?" decision. A partial push that
/// wrongly reports itself complete drops the null conjuncts silently here.
class ParquetHiveNullPredicateFixture : public sirius::test::GpuExecutionFixture {
 public:
  ParquetHiveNullPredicateFixture()
  {
    auto const root = dir_.file("hive");

    {
      scoped_sirius_disable disable_guard;
      duckdb::DuckDB gen_db(nullptr);
      duckdb::Connection gen(gen_db);
      for (auto const& sql : std::vector<std::string>{
             "CREATE TABLE hp (id INTEGER, v INTEGER, part INTEGER)",
             "INSERT INTO hp SELECT i,"
             "  CASE WHEN i % 3 = 0 THEN NULL ELSE i END,"
             "  i % 4"
             "  FROM range(1, 6001) AS t(i)",
             "COPY hp TO '" + root + "' (FORMAT PARQUET, PARTITION_BY (part))",
           }) {
        auto r = gen.Query(sql);
        REQUIRE(r);
        if (r->HasError()) { UNSCOPED_INFO("hive fixture setup error: " << r->GetError()); }
        REQUIRE_FALSE(r->HasError());
      }
    }

    scan_ = "read_parquet('" + root + "/part=*/*.parquet', hive_partitioning=true)";
  }

 protected:
  // Cleans itself up; see scratch_dir.
  sirius::test::scratch_dir dir_{"null_pred_hive"};
  std::string scan_;
};

}  // namespace

// The direct repro: a bare IS NULL predicate is what crashed.
TEST_CASE_METHOD(ParquetNullPredicateFixture,
                 "parquet IS NULL predicate does not crash row-group pruning",
                 "[integration][gpu_execution][scan][parquet][pushdown]")
{
  compare_gpu_vs_cpu("SELECT COUNT(*) FROM " + scan_ + " WHERE v IS NULL");
  compare_gpu_vs_cpu("SELECT COUNT(*) FROM " + scan_ + " WHERE v IS NOT NULL");
  compare_gpu_vs_cpu("SELECT COUNT(*) FROM " + scan_ + " WHERE s IS NULL");
}

// A mixed conjunct is the case where only PART of the predicate is pushed: the
// range side still goes to the reader for pruning, the null side is dropped and
// applied post-decode. The scan must therefore NOT be reported as fully
// row-filtered -- if it were, the dropped `v IS NULL` would never be applied
// and every row with id > 3000 would survive regardless of v.
//
// Row-level and ordered, not just COUNT: a partial-push bookkeeping error shows
// up as non-NULL v values appearing in the output.
TEST_CASE_METHOD(ParquetNullPredicateFixture,
                 "parquet partially-pushed conjunction still applies the null predicate",
                 "[integration][gpu_execution][scan][parquet][pushdown]")
{
  compare_gpu_vs_cpu("SELECT COUNT(*) FROM " + scan_ + " WHERE v IS NULL AND id > 3000");
  compare_gpu_vs_cpu("SELECT COUNT(*) FROM " + scan_ + " WHERE id < 100 AND v IS NULL");
  compare_gpu_vs_cpu_ordered("SELECT id, v FROM " + scan_ +
                             " WHERE v IS NULL AND id > 5940 ORDER BY id");
  compare_gpu_vs_cpu_ordered("SELECT id, v, s FROM " + scan_ +
                             " WHERE s IS NULL AND id BETWEEN 40 AND 80 ORDER BY id");
  // Two null conjuncts plus a range: everything but the range is dropped.
  compare_gpu_vs_cpu_ordered("SELECT id FROM " + scan_ +
                             " WHERE v IS NULL AND s IS NULL AND id < 100 ORDER BY id");
}

// Both sides reference the SAME column on purpose: TableFilterSet is keyed by
// column, so a cross-column form would either not be pushed down at all (OR) or
// be split into per-column filters whose top-level IS_NOT_NULL is dropped
// before the expression is built — leaving these branches unexercised.
//
// An OR cannot be split, so nothing is pushed.
TEST_CASE_METHOD(ParquetNullPredicateFixture,
                 "parquet un-splittable OR with a null predicate",
                 "[integration][gpu_execution][scan][parquet][pushdown]")
{
  compare_gpu_vs_cpu("SELECT COUNT(*) FROM " + scan_ + " WHERE v IS NULL OR v > 5000");
  compare_gpu_vs_cpu_ordered("SELECT id, v FROM " + scan_ +
                             " WHERE (v IS NULL OR v > 5990) AND id > 5900 ORDER BY id");
}

// A nested IS NOT NULL survives convert_table_filters_to_expression (which only
// drops it as a column's top-level filter) and lowers to IS_NULL + NOT in the
// cuDF AST, reaching the same stats-filter path.
//
// NOTE: any comparison on a column already implies it is non-null, so DuckDB's
// filter combiner may fold the IS NOT NULL away before it ever reaches us. The
// queries are correct either way; to confirm the branch was actually taken,
// check for the "pushing only the null-free conjuncts" debug line.
TEST_CASE_METHOD(ParquetNullPredicateFixture,
                 "parquet nested IS NOT NULL does not crash",
                 "[integration][gpu_execution][scan][parquet][pushdown]")
{
  compare_gpu_vs_cpu("SELECT COUNT(*) FROM " + scan_ + " WHERE v IS NOT NULL AND v > 3000");
  compare_gpu_vs_cpu_ordered("SELECT id, v FROM " + scan_ +
                             " WHERE v IS NOT NULL AND v < 60 ORDER BY id");
}

// Results, not just survival: the rows returned must still be correct now that
// the predicate is applied post-decode instead of by the reader.
TEST_CASE_METHOD(ParquetNullPredicateFixture,
                 "parquet null predicates return correct rows without pushdown",
                 "[integration][gpu_execution][scan][parquet][pushdown]")
{
  compare_gpu_vs_cpu_ordered("SELECT id, v FROM " + scan_ +
                             " WHERE v IS NULL AND id <= 60 ORDER BY id");
  compare_gpu_vs_cpu_ordered("SELECT id, v, s FROM " + scan_ +
                             " WHERE v IS NOT NULL AND id <= 60 ORDER BY id");
  compare_gpu_vs_cpu("SELECT COUNT(*), COUNT(v), COUNT(s) FROM " + scan_);
}

// ===========================================================================
// Hive-partitioned scans — the inline-assembly branch
// ===========================================================================

// A partial push treated as complete would leave `v IS NULL` unapplied here,
// returning every row with id > 3000 regardless of v.
TEST_CASE_METHOD(ParquetHiveNullPredicateFixture,
                 "parquet hive scan applies the null predicate after a partial push",
                 "[integration][gpu_execution][scan][parquet][pushdown][hive]")
{
  compare_gpu_vs_cpu("SELECT COUNT(*) FROM " + scan_ + " WHERE v IS NULL AND id > 3000");
  compare_gpu_vs_cpu_ordered("SELECT id, v FROM " + scan_ +
                             " WHERE v IS NULL AND id > 5940 ORDER BY id");
}

// Bare null predicate on a partitioned scan: nothing survives the split, so
// nothing is pushed at all and the whole predicate runs inline.
TEST_CASE_METHOD(ParquetHiveNullPredicateFixture,
                 "parquet hive scan with a bare null predicate",
                 "[integration][gpu_execution][scan][parquet][pushdown][hive]")
{
  compare_gpu_vs_cpu("SELECT COUNT(*) FROM " + scan_ + " WHERE v IS NULL");
  compare_gpu_vs_cpu("SELECT COUNT(*) FROM " + scan_ + " WHERE v IS NOT NULL");
}

// The partition column participates alongside the null predicate: partition
// values are injected during the same inline assembly that applies the filter.
TEST_CASE_METHOD(ParquetHiveNullPredicateFixture,
                 "parquet hive scan combining partition column and null predicate",
                 "[integration][gpu_execution][scan][parquet][pushdown][hive]")
{
  compare_gpu_vs_cpu("SELECT part, COUNT(*) FROM " + scan_ + " WHERE v IS NULL GROUP BY part");
  compare_gpu_vs_cpu_ordered("SELECT id, v, part FROM " + scan_ +
                             " WHERE v IS NULL AND part = 2 AND id > 5900 ORDER BY id");
}

// ===========================================================================
// Bare column-reference predicates
// ===========================================================================

// `WHERE flag` is a predicate that is nothing but a column reference. The stats
// rewrite replaces the reference with that row group's (min, max) pair, leaving
// two stats columns and no comparison to evaluate over them, and faults exactly
// like a null test does. Found by CI on the null-coverage branch.
//
// Nullability is irrelevant -- flag_dense contains no NULLs and faulted
// identically -- so this is about the predicate's shape, not its values.
TEST_CASE_METHOD(ParquetNullPredicateFixture,
                 "parquet bare boolean column predicate does not crash",
                 "[integration][gpu_execution][scan][parquet][pushdown]")
{
  compare_gpu_vs_cpu("SELECT COUNT(*) FROM " + scan_ + " WHERE flag");
  compare_gpu_vs_cpu("SELECT COUNT(*) FROM " + scan_ + " WHERE flag_dense");
  compare_gpu_vs_cpu_ordered("SELECT id, flag FROM " + scan_ +
                             " WHERE flag AND id > 5900 ORDER BY id");
}

// Shapes that are safe and must KEEP their pushdown -- a bare reference nested
// in a conjunction prunes fine, and so do NOT / IN / BETWEEN. Guards against a
// future widening of is_unsafe_for_stats_filter forfeiting pruning that works.
TEST_CASE_METHOD(ParquetNullPredicateFixture,
                 "parquet predicate shapes that remain pushable",
                 "[integration][gpu_execution][scan][parquet][pushdown]")
{
  compare_gpu_vs_cpu("SELECT COUNT(*) FROM " + scan_ + " WHERE flag AND v > 5000");
  compare_gpu_vs_cpu("SELECT COUNT(*) FROM " + scan_ + " WHERE NOT flag");
  compare_gpu_vs_cpu("SELECT COUNT(*) FROM " + scan_ + " WHERE v IN (1, 2, 3)");
  compare_gpu_vs_cpu("SELECT COUNT(*) FROM " + scan_ + " WHERE v BETWEEN 10 AND 20");
}
