[package]
name = "sirius-telemetry-server"
version.workspace = true
edition.workspace = true

[features]
ui = ["quent-query-engine-server/ui"]
swagger = ["quent-query-engine-server/swagger"]

[dependencies]
axum = "0.8"
clap = { version = "4", features = ["derive", "env"] }
sirius-telemetry-instrumentation = { path = "../instrumentation", features = ["collector"] }
sirius-telemetry-analyzer = { path = "../analyzer" }
sirius-telemetry-store = { path = "../store" }
nvtx-server = { git = "https://github.com/rapidsai/quent.git", rev = "fdf836950eab4df71189780b60ed1a5f34013c23" }
quent-analyzer = { git = "https://github.com/rapidsai/quent.git", rev = "fdf836950eab4df71189780b60ed1a5f34013c23" }
quent-io = { git = "https://github.com/rapidsai/quent.git", rev = "fdf836950eab4df71189780b60ed1a5f34013c23" }
quent-query-engine-analyzer = { git = "https://github.com/rapidsai/quent.git", rev = "fdf836950eab4df71189780b60ed1a5f34013c23" }
quent-query-engine-server = { git = "https://github.com/rapidsai/quent.git", rev = "fdf836950eab4df71189780b60ed1a5f34013c23" }
quent-store = { git = "https://github.com/rapidsai/quent.git", rev = "fdf836950eab4df71189780b60ed1a5f34013c23", features = ["io-msgpack", "io-ndjson", "io-postcard"] }
tokio = { version = "1", features = ["rt-multi-thread", "sync", "macros"] }
tracing = "0.1"
uuid = "1"

[build-dependencies]
quent-query-engine-ui = { git = "https://github.com/rapidsai/quent.git", rev = "fdf836950eab4df71189780b60ed1a5f34013c23" }
quent-ui = { git = "https://github.com/rapidsai/quent.git", rev = "fdf836950eab4df71189780b60ed1a5f34013c23" }
ts-rs = { version = "12", features = ["uuid-impl", "serde-json-impl"] }
