version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: cargo
    directories:
      - /rust
      - /experimental/starrocks
    schedule:
      interval: daily
