DROP TABLE IF EXISTS LINEITEM;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS PARTSUPP;
DROP TABLE IF EXISTS SUPPLIER;
DROP TABLE IF EXISTS PART;
DROP TABLE IF EXISTS NATION;
DROP TABLE IF EXISTS REGION;


CREATE TABLE REGION  (
    R_REGIONKEY  INTEGER NOT NULL UNIQUE PRIMARY KEY,
    R_NAME       CHAR(25) NOT NULL,
    R_COMMENT    VARCHAR(152),
);

CREATE TABLE NATION  (
    N_NATIONKEY  INTEGER NOT NULL UNIQUE PRIMARY KEY,
    N_NAME       CHAR(25) NOT NULL,
    N_REGIONKEY  INTEGER NOT NULL,
    N_COMMENT    VARCHAR(152),
);

CREATE TABLE PART  (
    P_PARTKEY     INTEGER NOT NULL UNIQUE PRIMARY KEY,
    P_NAME        VARCHAR(55) NOT NULL,
    P_MFGR        INTEGER NOT NULL,
    P_BRAND       INTEGER NOT NULL,
    P_TYPE        INTEGER NOT NULL,
    P_SIZE        INTEGER NOT NULL,
    P_CONTAINER   INTEGER NOT NULL,
    P_RETAILPRICE FLOAT NOT NULL,
    P_COMMENT     VARCHAR(23) NOT NULL,
);

CREATE TABLE SUPPLIER (
    S_SUPPKEY     INTEGER NOT NULL UNIQUE PRIMARY KEY,
    S_NAME        CHAR(25) NOT NULL,
    S_ADDRESS     VARCHAR(40) NOT NULL,
    S_NATIONKEY   INTEGER NOT NULL,
    S_PHONE       CHAR(15) NOT NULL,
    S_ACCTBAL     FLOAT NOT NULL,
    S_COMMENT     VARCHAR(101) NOT NULL,
);

CREATE TABLE PARTSUPP (
    PS_PARTKEY     INTEGER NOT NULL,
    PS_SUPPKEY     INTEGER NOT NULL,
    PS_AVAILQTY    INTEGER NOT NULL,
    PS_SUPPLYCOST  FLOAT NOT NULL,
    PS_COMMENT     VARCHAR(199) NOT NULL,
    CONSTRAINT PS_PARTSUPPKEY UNIQUE(PS_PARTKEY, PS_SUPPKEY)
);

CREATE TABLE CUSTOMER (
    C_CUSTKEY     INTEGER NOT NULL UNIQUE PRIMARY KEY,
    C_NAME        VARCHAR(25) NOT NULL,
    C_ADDRESS     VARCHAR(40) NOT NULL,
    C_NATIONKEY   INTEGER NOT NULL,
    C_PHONE       CHAR(15) NOT NULL,
    C_ACCTBAL     FLOAT  NOT NULL,
    C_MKTSEGMENT  INTEGER NOT NULL,
    C_COMMENT     VARCHAR(117) NOT NULL,
);

CREATE TABLE ORDERS  (
    O_ORDERKEY       INTEGER NOT NULL UNIQUE PRIMARY KEY,
    O_CUSTKEY        INTEGER NOT NULL,
    O_ORDERSTATUS    INTEGER NOT NULL,
    O_TOTALPRICE     FLOAT NOT NULL,
    O_ORDERDATE      INTEGER NOT NULL,
    O_ORDERPRIORITY  INTEGER NOT NULL,
    O_CLERK          INTEGER NOT NULL,
    O_SHIPPRIORITY   INTEGER NOT NULL,
    O_COMMENT        VARCHAR(79) NOT NULL,
);

CREATE TABLE LINEITEM (
    L_ORDERKEY    INTEGER NOT NULL,
    L_PARTKEY     INTEGER NOT NULL,
    L_SUPPKEY     INTEGER NOT NULL,
    L_LINENUMBER  INTEGER NOT NULL,
    L_QUANTITY    INTEGER NOT NULL,
    L_EXTENDEDPRICE  FLOAT NOT NULL,
    L_DISCOUNT    FLOAT NOT NULL,
    L_TAX         FLOAT NOT NULL,
    L_RETURNFLAG  INTEGER NOT NULL,
    L_LINESTATUS  INTEGER NOT NULL,
    L_SHIPDATE    INTEGER NOT NULL,
    L_COMMITDATE  INTEGER NOT NULL,
    L_RECEIPTDATE INTEGER NOT NULL,
    L_SHIPINSTRUCT INTEGER NOT NULL,
    L_SHIPMODE     INTEGER NOT NULL,
    L_COMMENT      VARCHAR(44) NOT NULL,
);

COPY lineitem FROM 'dbgen/s1/lineitem.tbl' WITH (HEADER false, DELIMITER '|');
COPY orders FROM 'dbgen/s1/orders.tbl' WITH (HEADER false, DELIMITER '|');
COPY supplier FROM 'dbgen/s1/supplier.tbl' WITH (HEADER false, DELIMITER '|');
COPY part FROM 'dbgen/s1/part.tbl' WITH (HEADER false, DELIMITER '|');
COPY customer FROM 'dbgen/s1/customer.tbl' WITH (HEADER false, DELIMITER '|');
COPY partsupp FROM 'dbgen/s1/partsupp.tbl' WITH (HEADER false, DELIMITER '|');
COPY nation FROM 'dbgen/s1/nation.tbl' WITH (HEADER false, DELIMITER '|');
COPY region FROM 'dbgen/s1/region.tbl' WITH (HEADER false, DELIMITER '|');

