[package]
name = "sirius-telemetry-store"
version.workspace = true
edition.workspace = true

[dependencies]
quent-analyzer = { git = "https://github.com/rapidsai/quent.git", rev = "35f8546dba50b2dbca4cf5e6f903c7970737ad7d" }
quent-events = { git = "https://github.com/rapidsai/quent.git", rev = "35f8546dba50b2dbca4cf5e6f903c7970737ad7d", features = ["serde"] }
quent-store = { git = "https://github.com/rapidsai/quent.git", rev = "35f8546dba50b2dbca4cf5e6f903c7970737ad7d" }
serde = { version = "1", features = ["derive"] }
smallvec = "1"

[build-dependencies]
quent-build-info = { git = "https://github.com/rapidsai/quent.git", rev = "35f8546dba50b2dbca4cf5e6f903c7970737ad7d" }
quent-store-build = { git = "https://github.com/rapidsai/quent.git", rev = "35f8546dba50b2dbca4cf5e6f903c7970737ad7d" }
quent-yaml = { git = "https://github.com/rapidsai/quent.git", rev = "35f8546dba50b2dbca4cf5e6f903c7970737ad7d" }
