// Identity of the code that turns a JIT cache key into a cubin.
#pragma once

namespace codegen::jit {

// Hash of the simpatico_jitgen objects (NVRTC options, embedded headers, key
// encoding), generated by cmake/jit_epoch.cmake. The on-disk cache
// namespaces cubins by it, so a build whose kernel generation differs never
// reads another build's cubins. 32 lowercase hex digits.
extern const char kJitEpoch[];

}  // namespace codegen::jit
