[package]
name = "telemetry-bridge"
version.workspace = true
edition.workspace = true

[lib]
name = "telemetry_bridge"
crate-type = ["staticlib"]

[dependencies]
cxx = "1"
instrumentation-model = { path = "../model" }

[build-dependencies]
cxx-build = "1"
instrumentation-model = { path = "../model" }
quent-codegen = { git = "https://github.com/rapidsai/quent.git", rev = "5f405cbf4f4b21bf9153669f2fa52baab51d2d10" }
