#!/usr/bin/env python3
"""Build a fixture where a deletion vector has been REPLACED by a later commit.

Run from the repo root:
    python3 test/cpp/integration/data/iceberg_v3_dv_replaced/generate.py
    python3 test/cpp/integration/data/iceberg_v3_dv_replaced/generate.py --verify

Why this fixture is hand-forged rather than generated by pyiceberg
------------------------------------------------------------------
pyiceberg 0.11.1 refuses to write delete files at all -- "Merge on read is not yet
supported, falling back to copy-on-write" -- so the conformance corpus cannot reach any
delete path, let alone a delete path that has been rewritten. Every other in-tree delete
fixture is a single snapshot in which every manifest entry is ADDED, which is the one
shape where reading a manifest as a picture of the present happens to be correct.

What it encodes
---------------
An Iceberg manifest is a LOG, not a picture. Compaction routinely REPLACES a deletion
vector: the superseded entry stays in the manifest at status=2 (DELETED) beside its
status=1 (ADDED) replacement, and both name the same `referenced_data_file`. A reader
that does not filter on status sees two vectors for one data file and keeps whichever it
processed last -- an order Iceberg attaches no meaning to.

So the retired entry is deliberately written LAST, and the two vectors delete DIFFERENT
rows, which makes the failure a visible row-count change rather than a coin flip:

    active  (status=1) deletes positions {1, 3}       -> 3 rows survive   <- correct
    retired (status=2) deletes positions {0, 1, 2, 4} -> 1 row survives   <- the bug

A reader that honours status returns 3 rows. One that does not returns 1. There is no
input on which both answers are defensible, which is what makes this a regression test
rather than a demonstration.
"""

import argparse
import json
import pathlib
import shutil
import struct
import sys
import zlib

HERE = pathlib.Path(__file__).resolve().parent
SRC = HERE.parent / "iceberg_v3_deletion_vector"
SRC_NAME = SRC.name
DST_NAME = HERE.name

PUFFIN_MAGIC = b"PFA1"
DV_MAGIC = bytes([0xD1, 0xD3, 0x39, 0x64])

TOTAL_ROWS = 5
ACTIVE_POSITIONS = [1, 3]
RETIRED_POSITIONS = [0, 1, 2, 4]

STATUS_ADDED = 1
STATUS_DELETED = 2


def roaring64(positions):
    """Serialize a portable 64-bit Roaring bitmap.

    Layout: [8B LE bitmap count] { [4B LE high key] [32-bit Roaring bitmap] } x N, with each
    32-bit bitmap as SERIAL_COOKIE_NO_RUNCONTAINER (12346) + container count + descriptive
    header + offset header + array containers. Byte-for-byte identical to what the existing
    iceberg_v3_deletion_vector blob carries, which is how this encoder was validated.
    """
    by_high = {}
    for p in sorted(set(positions)):
        by_high.setdefault(p >> 32, []).append(p & 0xFFFFFFFF)

    out = struct.pack("<q", len(by_high))
    for high, values in sorted(by_high.items()):
        out += struct.pack("<I", high)
        containers = {}
        for v in values:
            containers.setdefault(v >> 16, []).append(v & 0xFFFF)
        keys = sorted(containers)

        out += struct.pack("<I", 12346) + struct.pack("<I", len(keys))
        for k in keys:
            out += struct.pack("<HH", k, len(containers[k]) - 1)

        offset = 4 + 4 + 4 * len(keys) + 4 * len(keys)
        for k in keys:
            out += struct.pack("<I", offset)
            offset += 2 * len(containers[k])

        for k in keys:
            for v in containers[k]:
                out += struct.pack("<H", v)
    return out


def dv_blob(positions):
    """deletion-vector-v1: [4B BE length of magic+vector][magic][vector][4B BE CRC-32]."""
    body = DV_MAGIC + roaring64(positions)
    return (
        struct.pack(">I", len(body))
        + body
        + struct.pack(">I", zlib.crc32(body) & 0xFFFFFFFF)
    )


def build_puffin(blob, referenced_data_file, cardinality):
    """Wrap ONE vector in its own Puffin container.

    One file per vector, because that is what a rewrite actually produces: compaction writes a
    NEW Puffin file and marks the old file's manifest entry DELETED. Putting both vectors in one
    container instead makes the fixture untestable -- readers that key decoded vectors by
    `referenced-data-file` (pyiceberg does) collide on the shared key and pick one by position,
    so the answer stops depending on the manifest status this fixture exists to exercise.

    `snapshot-id` and `sequence-number` are -1 because the Puffin spec fixes them there for
    `deletion-vector-v1`: the file is written before a snapshot id exists to record. `cardinality`
    is required, and is a string because Puffin properties are a string->string map.
    """
    descriptor = {
        "type": "deletion-vector-v1",
        "fields": [],
        "snapshot-id": -1,
        "sequence-number": -1,
        "offset": len(PUFFIN_MAGIC),
        "length": len(blob),
        "properties": {
            "referenced-data-file": referenced_data_file,
            "cardinality": str(cardinality),
        },
    }
    footer = json.dumps(
        {"blobs": [descriptor], "properties": {}}, separators=(",", ":")
    ).encode()

    return (
        PUFFIN_MAGIC
        + blob
        + PUFFIN_MAGIC
        + footer
        + struct.pack("<i", len(footer))
        + b"\x00\x00\x00\x00"  # flags: bit 0 clear = uncompressed footer
        + PUFFIN_MAGIC
    ), descriptor


def retarget(value):
    """Repoint a fixture-relative path at this fixture."""
    if isinstance(value, str):
        return value.replace(SRC_NAME, DST_NAME)
    return value


def rewrite_paths(obj):
    if isinstance(obj, dict):
        return {k: rewrite_paths(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [rewrite_paths(v) for v in obj]
    return retarget(obj)


def verify():
    """Check the container with a reader we did not write, then re-derive both cardinalities."""
    import fastavro
    from pyiceberg.table.puffin import PuffinFile

    puffins = sorted((HERE / "data").glob("*.puffin"))
    if len(puffins) != 2:
        print(
            f"  expected 2 Puffin files (active + retired), found {len(puffins)}",
            file=sys.stderr,
        )
        return False
    for path in puffins:
        blobs = PuffinFile(path.read_bytes()).footer.blobs
        print(
            f"  pyiceberg: OK - {path.name}: {len(blobs)} blob(s), type={blobs[0].type}"
        )

    manifest = next(p for p in (HERE / "metadata").glob("*-m1.avro"))
    with manifest.open("rb") as fh:
        entries = [r for r in fastavro.reader(fh)]

    puffin_entries = [
        r
        for r in entries
        if (r["data_file"].get("file_format") or "").upper() == "PUFFIN"
    ]
    statuses = [r["status"] for r in puffin_entries]
    print(
        f"  manifest: {len(puffin_entries)} PUFFIN entries, statuses in order {statuses}"
    )

    if statuses != [STATUS_ADDED, STATUS_DELETED]:
        print(
            f"  the retired entry must come LAST so order-dependent readers pick it; got {statuses}",
            file=sys.stderr,
        )
        return False

    referenced = {r["data_file"]["referenced_data_file"] for r in puffin_entries}
    if len(referenced) != 1:
        print(
            f"  both entries must name ONE data file; got {referenced}", file=sys.stderr
        )
        return False

    for entry, expected in zip(puffin_entries, (ACTIVE_POSITIONS, RETIRED_POSITIONS)):
        if entry["data_file"]["record_count"] != len(expected):
            print(
                f"  record_count {entry['data_file']['record_count']} != cardinality {len(expected)}",
                file=sys.stderr,
            )
            return False

    # The structural checks above all passed on a fixture whose data manifest still pointed at
    # the source fixture, so referenced_data_file matched nothing and NEITHER vector applied.
    # Only scanning it caught that. Assert on the answer an independent reader actually returns.
    from pyiceberg.table import StaticTable

    expected = TOTAL_ROWS - len(ACTIVE_POSITIONS)
    rows = (
        StaticTable.from_metadata(str(HERE / "metadata" / "v1.metadata.json"))
        .scan()
        .to_arrow()
        .num_rows
    )

    if rows != expected:
        blind = TOTAL_ROWS - len(set(ACTIVE_POSITIONS) | set(RETIRED_POSITIONS))
        hint = {
            TOTAL_ROWS: "NEITHER vector applied - referenced_data_file matches no data file",
            blind: "both vectors applied - the retired entry was not filtered out",
        }.get(rows, "unexpected")
        print(
            f"  pyiceberg scan: FAIL - {rows} rows, expected {expected} ({hint})",
            file=sys.stderr,
        )
        return False

    print(f"  pyiceberg scan: OK - {rows} rows, deletes {ACTIVE_POSITIONS} applied")
    print(
        f"  a status-blind reader would instead return {TOTAL_ROWS - len(RETIRED_POSITIONS)}"
    )
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--verify", action="store_true", help="validate only, write nothing"
    )
    args = ap.parse_args()

    if args.verify:
        print(f"verifying {DST_NAME}")
        return 0 if verify() else 1

    import fastavro

    if not SRC.is_dir():
        print(f"source fixture missing: {SRC}", file=sys.stderr)
        return 1

    # Rebuild from the sibling fixture each run so the two cannot drift apart.
    for child in HERE.iterdir():
        if child.name != pathlib.Path(__file__).name:
            shutil.rmtree(child) if child.is_dir() else child.unlink()

    for sub in ("data", "metadata"):
        shutil.copytree(SRC / sub, HERE / sub)
    for stray in list((HERE / "data").glob("*.bak")) + list(
        (HERE / "metadata").glob("*.bak")
    ):
        stray.unlink()
    for stray in (HERE / "metadata").glob("*.py"):
        stray.unlink()

    # --- table metadata + manifest list: repoint every path at this fixture -----------------
    meta_path = HERE / "metadata" / "v1.metadata.json"
    meta = rewrite_paths(json.loads(meta_path.read_text()))
    meta_path.write_text(json.dumps(meta, indent=2))

    # EVERY avro carries paths rooted at the repo, the DATA manifest included. Missing one leaves
    # the vectors pointing at the source fixture's parquet, so referenced_data_file matches no
    # file this scan reads and the deletes are silently skipped -- a 5-row answer that reads as a
    # healthy table rather than a broken fixture.
    for avro_path in sorted((HERE / "metadata").glob("*.avro")):
        with avro_path.open("rb") as fh:
            reader = fastavro.reader(fh)
            schema, records = reader.writer_schema, [rewrite_paths(r) for r in reader]
        with avro_path.open("wb") as fh:
            fastavro.writer(fh, schema, records, codec="null")

    list_path = next((HERE / "metadata").glob("snap-*.avro"))
    with list_path.open("rb") as fh:
        reader = fastavro.reader(fh)
        list_schema, list_records = reader.writer_schema, list(reader)

    # --- one Puffin file per vector, as a rewrite produces ----------------------------------
    # The one data file both vectors claim, named exactly as the data manifest names it.
    data_manifest = next((HERE / "metadata").glob("*-m0.avro"))
    with data_manifest.open("rb") as fh:
        data_file = next(r["data_file"]["file_path"] for r in fastavro.reader(fh))

    next((HERE / "data").glob("*.puffin")).unlink()
    data_dir = HERE / "data"
    descriptors = {}
    for label, positions in (
        ("active", ACTIVE_POSITIONS),
        ("retired", RETIRED_POSITIONS),
    ):
        container, descriptor = build_puffin(
            dv_blob(positions), data_file, len(positions)
        )
        path = (
            data_dir / f"dv-{label}-00000-0-d7e8f9a0-0007-0007-0007-000000000002.puffin"
        )
        path.write_bytes(container)
        descriptors[label] = (
            f"{HERE.relative_to(pathlib.Path.cwd())}/data/{path.name}",
            descriptor,
        )
        print(f"wrote {path.name}: {len(container)}B, {len(positions)} position(s)")

    # --- the delete manifest: ADDED first, DELETED last -------------------------------------
    manifest_path = next((HERE / "metadata").glob("*-m1.avro"))
    with manifest_path.open("rb") as fh:
        reader = fastavro.reader(fh)
        schema, records = reader.writer_schema, list(reader)

    template = next(
        r
        for r in records
        if (r["data_file"].get("file_format") or "").upper() == "PUFFIN"
    )
    others = [
        r
        for r in records
        if (r["data_file"].get("file_format") or "").upper() != "PUFFIN"
    ]

    rebuilt = []
    for status, positions, label in (
        (STATUS_ADDED, ACTIVE_POSITIONS, "active"),
        (STATUS_DELETED, RETIRED_POSITIONS, "retired"),
    ):
        puffin_rel, descriptor = descriptors[label]
        entry = rewrite_paths(json.loads(json.dumps(template)))
        entry["status"] = status
        df = entry["data_file"]
        df["file_path"] = puffin_rel
        df["referenced_data_file"] = data_file
        df["content_offset"] = descriptor["offset"]
        df["content_size_in_bytes"] = descriptor["length"]
        df["record_count"] = len(positions)
        rebuilt.append(entry)

    with manifest_path.open("wb") as fh:
        fastavro.writer(fh, schema, others + rebuilt, codec="null")
    print(
        f"wrote {manifest_path.name}: statuses {[r['status'] for r in rebuilt]} (DELETED last)"
    )

    with list_path.open("wb") as fh:
        fastavro.writer(fh, list_schema, list_records, codec="null")

    print("validating:")
    return 0 if verify() else 1


if __name__ == "__main__":
    raise SystemExit(main())
