[workspace]
channels = ["conda-forge"]
name = "sirius-duckdb"
platforms = ["linux-64", "linux-aarch64"]
version = "0.0.0"

[tasks]

[dependencies]
black = "*"
cmake-format = "*"
make = "*"
python = "3.*"

[feature.tidy.dependencies]
clang = "*"
clang-tools = "*"
cmake = "4.4.*"
cxx-compiler = "*"
cuda-nvcc = "*"
cuda-driver-dev = "*"
cuda-nvml-dev = "*"
ninja = "*"
sccache = "0.18.*"

[feature.format.pypi-dependencies]
clang-format = ">=11,<12"

[environments]
default = ["tidy"]
format = ["format"]
