# 8-CN SF1000 knobs. Measured 2026-08-28 on gcn-09+gcn-18:
# 128/32, pipeline_dop=18, uring, fabric → 22/22, 1.44× geomean vs 4-GPU GPFS.
# 16 GiB staging exhausted. dop=36 + kvikio was 1.21× slower than 4-GPU.

export SCALE_FACTOR=1000
export NUM_CNS_PER_HOST=${NUM_CNS_PER_HOST:-4}
export NUM_CNS=${NUM_CNS:-8}

export GPU_MEM=${GPU_MEM:-128GiB}
export HOST_MEM=${HOST_MEM:-112GiB}
export STAGING=${STAGING:-32GiB}
export SIRIUS_EXCHANGE_STAGING_BYTES=${SIRIUS_EXCHANGE_STAGING_BYTES:-$STAGING}

export SIRIUS_EXCHANGE_STAGING_ARENA=${SIRIUS_EXCHANGE_STAGING_ARENA:-fabric}
export UCX_TLS=${UCX_TLS:-cuda_copy,cuda_ipc,tcp,self}
export SIRIUS_CN_USE_SIRIUS_DATASOURCE=${SIRIUS_CN_USE_SIRIUS_DATASOURCE:-true}

export SIRIUS_QUERY_WATCHDOG_SECS=${SIRIUS_QUERY_WATCHDOG_SECS:-300}
export SIRIUS_CN_RPC_TIMEOUT_SECS=${SIRIUS_CN_RPC_TIMEOUT_SECS:-300}
export SIRIUS_CN_NIXL_WARMUP_TIMEOUT_SECS=${SIRIUS_CN_NIXL_WARMUP_TIMEOUT_SECS:-300}

export PIPELINE_DOP=${PIPELINE_DOP:-18}
export FE_QUERY_TIMEOUT=${FE_QUERY_TIMEOUT:-1800}
export QUERY_TIMEOUT=${QUERY_TIMEOUT:-1800}
export COLD_TIMEOUT=${COLD_TIMEOUT:-6000}
export MIN_BACKENDS=${MIN_BACKENDS:-8}

export TPCH_DATA=${TPCH_DATA:-/scratch/sirius/datasets/tpch_sf1000}
export Q11_FRACTION=${Q11_FRACTION:-0.000000100000}
