# Transitively scan the CCCL (<cuda/std/...>, <cub/...>) #include closure the
# runtime NVRTC JIT needs, and emit a .cpp that embeds each header as a
# raw-string literal exposed as an EmbeddedJitHeader table. Passing these to
# nvrtcCreateProgram() as named in-memory headers lets the JIT compile with NO
# -I into a CCCL tree, so a binary distribution needs only the driver + the
# nvrtc runtime it already links. Invoked via `cmake -P`.
#
# Required -D inputs: CCCL_DIR is the build-time CCCL include root containing
# cuda/, cub/, and thrust/; OUT is the path of the .cpp to generate. DEPFILE is
# optional and names a Make/Ninja depfile for the transitively scanned headers.
#
# The scan follows every literal `#include` line (both #ifdef branches) from the
# fixed kernel-prelude roots below. Dependencies reached through macro-expanded
# includes must be seeded explicitly. Recomputed at build time, so it tracks the
# CCCL version in use.

cmake_minimum_required(VERSION 3.24)

if(NOT IS_DIRECTORY "${CCCL_DIR}")
  message(
    FATAL_ERROR "embed_cccl_headers: CCCL_DIR '${CCCL_DIR}' is not a directory")
endif()
foreach(marker cub/version.cuh cuda/std/cstdint thrust/version.h)
  if(NOT EXISTS "${CCCL_DIR}/${marker}")
    message(
      FATAL_ERROR
        "embed_cccl_headers: CCCL_DIR '${CCCL_DIR}' is missing '${marker}'")
  endif()
endforeach()

# Union of the includes emitted by the encode + decode kernel preludes. CUDA 12
# reaches execution_policy.h through a macro-expanded include, which the
# literal-include scanner cannot discover, so seed it explicitly.
set(roots
    cub/block/block_reduce.cuh
    cub/block/block_scan.cuh
    cub/block/block_exchange.cuh
    cuda/std/cstdint
    cuda/std/cstddef
    cuda/std/climits
    cuda/std/type_traits
    thrust/system/cpp/detail/execution_policy.h
    thrust/system/cuda/detail/execution_policy.h)

set(worklist ${roots})
set(found "")

while(worklist)
  list(POP_FRONT worklist rel)
  if(rel IN_LIST found)
    continue()
  endif()
  set(abs "${CCCL_DIR}/${rel}")
  if(NOT EXISTS "${abs}" OR IS_DIRECTORY "${abs}")
    continue()
  endif()
  list(APPEND found "${rel}")

  file(READ "${abs}" content)
  get_filename_component(curdir "${rel}" DIRECTORY)
  # Anchor to line start (a newline followed by only whitespace then '#') so we
  # don't match example `#include` lines inside doc comments — those would drag
  # in large unused subtrees (e.g. all of thrust/). A leading newline is
  # prepended so a directive on the first line still matches.
  string(REGEX MATCHALL "[\r\n][ \t]*#[ \t]*include[ \t]*[<\"][^>\"\r\n]+[>\"]"
               incs "\n${content}")
  foreach(inc IN LISTS incs)
    string(REGEX REPLACE ".*[<\"]([^>\"]+)[>\"].*" "\\1" name "${inc}")
    set(resolved "")
    # 1) resolve relative to the CCCL root (covers <cuda/...>, <cub/...>)
    cmake_path(SET cand NORMALIZE "${CCCL_DIR}/${name}")
    if(EXISTS "${cand}" AND NOT IS_DIRECTORY "${cand}")
      cmake_path(RELATIVE_PATH cand BASE_DIRECTORY "${CCCL_DIR}"
                 OUTPUT_VARIABLE resolved)
    elseif(curdir)
      # 2) resolve relative to the including file's directory (quoted includes)
      cmake_path(SET cand2 NORMALIZE "${CCCL_DIR}/${curdir}/${name}")
      string(FIND "${cand2}" "${CCCL_DIR}/" pos)
      if(pos EQUAL 0
         AND EXISTS "${cand2}"
         AND NOT IS_DIRECTORY "${cand2}")
        cmake_path(RELATIVE_PATH cand2 BASE_DIRECTORY "${CCCL_DIR}"
                   OUTPUT_VARIABLE resolved)
      endif()
    endif()
    # Names that don't resolve under CCCL are nvrtc built-ins or host headers
    # guarded out under __CUDACC_RTC__ — skip them.
    if(resolved AND NOT resolved IN_LIST found)
      list(APPEND worklist "${resolved}")
    endif()
  endforeach()
endwhile()

list(REMOVE_DUPLICATES found)
list(SORT found)
list(LENGTH found n)
if(n EQUAL 0)
  message(FATAL_ERROR "embed_cccl_headers: the scanned CCCL closure is empty")
endif()

# Raw-string delimiter (<=16 chars, C++ limit) chosen so it cannot appear in a
# CCCL header.
set(D "CCCL_EMB_9F3A")
set(body "// AUTO-GENERATED by embed_cccl_headers.cmake -- DO NOT EDIT.\n")
string(APPEND body
       "// ${n} CCCL headers, the runtime NVRTC JIT include closure.\n")
string(APPEND body "#include \"codegen/jit/cccl_embedded_headers.h\"\n")
string(APPEND body "namespace codegen::jit {\n")

set(idx 0)
set(_fingerprint_manifest "")
foreach(rel IN LISTS found)
  file(READ "${CCCL_DIR}/${rel}" hsrc)
  # Hash each source independently, then hash an unambiguous ordered manifest.
  # This avoids retaining a second full copy of the (large) closure while still
  # binding the final fingerprint to every relative name and byte of content.
  string(SHA256 hsrc_sha256 "${hsrc}")
  string(LENGTH "${rel}" rel_length)
  string(APPEND _fingerprint_manifest "${rel_length}:${rel}:${hsrc_sha256}\n")
  string(APPEND body "static const char* kCcclName${idx} = \"${rel}\";\n")
  string(APPEND body
         "static const char* kCcclSrc${idx} =\nR\"${D}(${hsrc})${D}\";\n")
  math(EXPR idx "${idx}+1")
endforeach()
string(SHA256 cccl_fingerprint "${_fingerprint_manifest}")
string(TOLOWER "${cccl_fingerprint}" cccl_fingerprint)
string(
  APPEND body
  "const char kCcclEmbeddedHeadersFingerprint[] = \"${cccl_fingerprint}\";\n")

string(APPEND body "const EmbeddedJitHeader kCcclEmbeddedHeaders[] = {\n")
set(idx 0)
foreach(rel IN LISTS found)
  string(APPEND body "  {kCcclName${idx}, kCcclSrc${idx}},\n")
  math(EXPR idx "${idx}+1")
endforeach()
string(APPEND body "};\n")
string(APPEND body "const int kCcclEmbeddedHeaderCount = ${n};\n")
string(APPEND body "}  // namespace codegen::jit\n")

get_filename_component(out_dir "${OUT}" DIRECTORY)
file(MAKE_DIRECTORY "${out_dir}")
file(WRITE "${OUT}" "${body}")

# Teach the build graph about the dynamically discovered closure. If any scanned
# header changes (including gaining a new literal include), the custom command
# reruns and discovers the updated closure.
if(DEFINED DEPFILE AND NOT DEPFILE STREQUAL "")
  # Escape a path for a Make/Ninja depfile and return it through output.
  function(escape_depfile_path input output)
    set(escaped "${input}")
    string(REPLACE "\\" "/" escaped "${escaped}")
    string(REPLACE "$" "$$" escaped "${escaped}")
    string(REPLACE "#" "\\#" escaped "${escaped}")
    string(REPLACE " " "\\ " escaped "${escaped}")
    string(REPLACE ":" "\\:" escaped "${escaped}")
    set(${output}
        "${escaped}"
        PARENT_SCOPE)
  endfunction()

  get_filename_component(depfile_dir "${DEPFILE}" DIRECTORY)
  file(MAKE_DIRECTORY "${depfile_dir}")
  escape_depfile_path("${OUT}" depfile_out)
  set(_depfile_body "${depfile_out}:")
  foreach(rel IN LISTS found)
    escape_depfile_path("${CCCL_DIR}/${rel}" depfile_header)
    string(APPEND _depfile_body " \\\n  ${depfile_header}")
  endforeach()
  string(APPEND _depfile_body "\n")
  file(WRITE "${DEPFILE}" "${_depfile_body}")
endif()

message(
  STATUS
    "embed_cccl_headers: embedded ${n} CCCL headers (${cccl_fingerprint}) into ${OUT}"
)
