# Embed the complete approved CCCL library trees, not an include closure.
# INCLUDE_DIRS_FILE contains CMake's evaluated include roots in search order.
# OUT names the generated .cpp; DEPFILE optionally tracks files and directories
# so content edits, additions, removals, and search-root shadowing regenerate
# it.
cmake_minimum_required(VERSION 3.24)
file(STRINGS "${INCLUDE_DIRS_FILE}" include_dirs)

set(names "")
set(dependencies "")
foreach(include_dir IN LISTS include_dirs)
  if(NOT IS_ABSOLUTE "${include_dir}")
    message(
      FATAL_ERROR "CCCL include directory must be absolute: ${include_dir}")
  endif()
  # Track even a currently absent earlier root: creating it may shadow headers.
  set(parent "${include_dir}")
  while(NOT IS_DIRECTORY "${parent}")
    get_filename_component(parent "${parent}" DIRECTORY)
  endwhile()
  list(APPEND dependencies "${parent}")
  foreach(component cub thrust cuda nv)
    file(
      GLOB_RECURSE entries FOLLOW_SYMLINKS
      LIST_DIRECTORIES TRUE
      RELATIVE "${include_dir}"
      "${include_dir}/${component}/*")
    # Track the component root too, including an empty directory.
    if(IS_DIRECTORY "${include_dir}/${component}")
      list(APPEND dependencies "${include_dir}/${component}")
    endif()
    foreach(name IN LISTS entries)
      if(IS_DIRECTORY "${include_dir}/${name}")
        list(APPEND dependencies "${include_dir}/${name}")
      else()
        list(APPEND names "${name}")
      endif()
    endforeach()
  endforeach()
endforeach()
list(REMOVE_DUPLICATES names)
list(SORT names)
list(LENGTH names count)
foreach(marker cub/version.cuh cuda/std/cstdint thrust/version.h)
  if(NOT marker IN_LIST names)
    message(
      FATAL_ERROR "CCCL header '${marker}' is missing from: ${include_dirs}")
  endif()
endforeach()

set(D "CCCL_EMB_9F3A")
set(body "// AUTO-GENERATED by embed_cccl_headers.cmake -- DO NOT EDIT.\n")
string(APPEND body
       "// ${count} headers from the complete CCCL library bundle.\n")
string(
  APPEND body
  "#include \"codegen/jit/cccl_embedded_headers.h\"\nnamespace codegen::jit {\n"
)
string(APPEND body "const EmbeddedJitHeader kCcclEmbeddedHeaders[] = {\n")
foreach(name IN LISTS names)
  foreach(include_dir IN LISTS include_dirs)
    set(header "${include_dir}/${name}")
    if(EXISTS "${header}" AND NOT IS_DIRECTORY "${header}")
      break()
    endif()
  endforeach()
  list(APPEND dependencies "${header}")
  file(READ "${header}" content)
  string(FIND "${content}" ")${D}\"" delimiter_collision)
  if(NOT delimiter_collision EQUAL -1)
    message(FATAL_ERROR "Embedded raw-string delimiter occurs in ${header}")
  endif()
  string(APPEND body "  {\"${name}\", R\"${D}(${content})${D}\"},\n")
endforeach()
string(APPEND body "};\nconst int kCcclEmbeddedHeaderCount = ${count};\n")
string(APPEND body "}  // namespace codegen::jit\n")
file(WRITE "${OUT}" "${body}")

if(DEFINED DEPFILE AND NOT DEPFILE STREQUAL "")
  # Escape Make/Ninja depfile syntax, including roots containing spaces.
  function(escape_depfile_path input output)
    set(escaped "${input}")
    string(REPLACE "\\" "/" escaped "${escaped}")
    string(REPLACE "$" "$$" escaped "${escaped}")
    string(REPLACE "#" "\\#" escaped "${escaped}")
    string(REPLACE " " "\\ " escaped "${escaped}")
    string(REPLACE ":" "\\:" escaped "${escaped}")
    set(${output}
        "${escaped}"
        PARENT_SCOPE)
  endfunction()
  escape_depfile_path("${OUT}" escaped_output)
  set(depfile "${escaped_output}:")
  list(REMOVE_DUPLICATES dependencies)
  foreach(dependency IN LISTS dependencies)
    escape_depfile_path("${dependency}" escaped_dependency)
    string(APPEND depfile " \\\n  ${escaped_dependency}")
  endforeach()
  file(WRITE "${DEPFILE}" "${depfile}\n")
endif()
message(STATUS "Embedded ${count} CCCL headers into ${OUT}")
