# Transitively scan the CCCL (<cuda/std/...>, <cub/...>) #include closure the
# runtime NVRTC JIT needs, and emit a .cpp that embeds each header as a
# raw-string literal exposed as an EmbeddedJitHeader table. Passing these to
# nvrtcCreateProgram() as named in-memory headers lets the JIT compile with NO
# -I into a CCCL tree, so a binary distribution needs only the driver + the
# nvrtc runtime it already links. Invoked via `cmake -P`.
#
# Inputs (-D): CCCL_DIR  the build-time CCCL include root (contains cuda/, cub/,
# and thrust/) OUT       path of the .cpp to generate
#
# The scan follows every literal `#include` line (both #ifdef branches) from the
# fixed kernel-prelude roots below. Dependencies reached through macro-expanded
# includes must be seeded explicitly. Recomputed at build time, so it tracks the
# CCCL version in use.

cmake_minimum_required(VERSION 3.24)

if(NOT IS_DIRECTORY "${CCCL_DIR}")
  message(
    FATAL_ERROR "embed_cccl_headers: CCCL_DIR '${CCCL_DIR}' is not a directory")
endif()

# Union of the includes emitted by the encode + decode kernel preludes. CUDA 12
# reaches execution_policy.h through a macro-expanded include, which the
# literal-include scanner cannot discover, so seed it explicitly.
set(roots
    cub/block/block_reduce.cuh
    cub/block/block_scan.cuh
    cub/block/block_exchange.cuh
    cuda/std/cstdint
    cuda/std/cstddef
    cuda/std/climits
    cuda/std/type_traits
    thrust/system/cpp/detail/execution_policy.h
    thrust/system/cuda/detail/execution_policy.h)

set(worklist ${roots})
set(found "")

while(worklist)
  list(POP_FRONT worklist rel)
  if(rel IN_LIST found)
    continue()
  endif()
  set(abs "${CCCL_DIR}/${rel}")
  if(NOT EXISTS "${abs}" OR IS_DIRECTORY "${abs}")
    continue()
  endif()
  list(APPEND found "${rel}")

  file(READ "${abs}" content)
  get_filename_component(curdir "${rel}" DIRECTORY)
  # Anchor to line start (a newline followed by only whitespace then '#') so we
  # don't match example `#include` lines inside doc comments — those would drag
  # in large unused subtrees (e.g. all of thrust/). A leading newline is
  # prepended so a directive on the first line still matches.
  string(REGEX MATCHALL "[\r\n][ \t]*#[ \t]*include[ \t]*[<\"][^>\"\r\n]+[>\"]"
               incs "\n${content}")
  foreach(inc IN LISTS incs)
    string(REGEX REPLACE ".*[<\"]([^>\"]+)[>\"].*" "\\1" name "${inc}")
    set(resolved "")
    # 1) resolve relative to the CCCL root (covers <cuda/...>, <cub/...>)
    cmake_path(SET cand NORMALIZE "${CCCL_DIR}/${name}")
    if(EXISTS "${cand}" AND NOT IS_DIRECTORY "${cand}")
      cmake_path(RELATIVE_PATH cand BASE_DIRECTORY "${CCCL_DIR}"
                 OUTPUT_VARIABLE resolved)
    elseif(curdir)
      # 2) resolve relative to the including file's directory (quoted includes)
      cmake_path(SET cand2 NORMALIZE "${CCCL_DIR}/${curdir}/${name}")
      string(FIND "${cand2}" "${CCCL_DIR}/" pos)
      if(pos EQUAL 0
         AND EXISTS "${cand2}"
         AND NOT IS_DIRECTORY "${cand2}")
        cmake_path(RELATIVE_PATH cand2 BASE_DIRECTORY "${CCCL_DIR}"
                   OUTPUT_VARIABLE resolved)
      endif()
    endif()
    # Names that don't resolve under CCCL are nvrtc built-ins or host headers
    # guarded out under __CUDACC_RTC__ — skip them.
    if(resolved AND NOT resolved IN_LIST found)
      list(APPEND worklist "${resolved}")
    endif()
  endforeach()
endwhile()

list(REMOVE_DUPLICATES found)
list(SORT found)
list(LENGTH found n)

# Raw-string delimiter (<=16 chars, C++ limit) chosen so it cannot appear in a
# CCCL header.
set(D "CCCL_EMB_9F3A")
set(body "// AUTO-GENERATED by embed_cccl_headers.cmake -- DO NOT EDIT.\n")
string(APPEND body
       "// ${n} CCCL headers, the runtime NVRTC JIT include closure.\n")
string(APPEND body "#include \"codegen/jit/cccl_embedded_headers.h\"\n")
string(APPEND body "namespace codegen::jit {\n")

set(idx 0)
foreach(rel IN LISTS found)
  file(READ "${CCCL_DIR}/${rel}" hsrc)
  string(APPEND body "static const char* kCcclName${idx} = \"${rel}\";\n")
  string(APPEND body
         "static const char* kCcclSrc${idx} =\nR\"${D}(${hsrc})${D}\";\n")
  math(EXPR idx "${idx}+1")
endforeach()

string(APPEND body "const EmbeddedJitHeader kCcclEmbeddedHeaders[] = {\n")
set(idx 0)
foreach(rel IN LISTS found)
  string(APPEND body "  {kCcclName${idx}, kCcclSrc${idx}},\n")
  math(EXPR idx "${idx}+1")
endforeach()
string(APPEND body "};\n")
string(APPEND body "const int kCcclEmbeddedHeaderCount = ${n};\n")
string(APPEND body "}  // namespace codegen::jit\n")

file(WRITE "${OUT}" "${body}")
message(STATUS "embed_cccl_headers: embedded ${n} CCCL headers into ${OUT}")
