# Generate a header that embeds the project headers the runtime NVRTC JIT
# #includes, as raw-string literals, so a binary distribution needs no simpatico
# source tree on disk. Invoked via `cmake -P` from an add_custom_command.
#
# Inputs (passed with -D): IN_STDINT  path to include/codegen/stdint_shim.hpp
# IN_RLE     path to include/codegen/decode/rle_block.cuh OUT        path of the
# header to generate
#
# The embedded contents are handed to nvrtcCreateProgram() as named in-memory
# headers, so the include NAMES below must match the `#include "..."` strings
# used by the rendered kernel sources exactly.

file(READ "${IN_STDINT}" STDINT_SRC)
file(READ "${IN_RLE}" RLE_SRC)

# Raw-string delimiter chosen so it cannot appear in the embedded C++ source.
set(D "SIMPATICO_EMBED")

file(
  WRITE "${OUT}"
  "// AUTO-GENERATED by embed_jit_headers.cmake -- DO NOT EDIT.\n"
  "// Project headers the runtime NVRTC JIT #includes, embedded as in-memory\n"
  "// headers so a binary distribution needs no simpatico source tree on disk.\n"
  "#pragma once\n"
  "#include \"codegen/jit/embedded_header.h\"\n"
  "namespace codegen::jit {\n"
  "inline constexpr const char* kEmbeddedJitHeaderStdintShim =\n"
  "R\"${D}(${STDINT_SRC})${D}\";\n"
  "inline constexpr const char* kEmbeddedJitHeaderRleBlock =\n"
  "R\"${D}(${RLE_SRC})${D}\";\n"
  "// Names MUST match the `#include \"...\"` strings in the rendered kernels.\n"
  "inline constexpr EmbeddedJitHeader kEmbeddedJitHeaders[] = {\n"
  "  {\"codegen/stdint_shim.hpp\", kEmbeddedJitHeaderStdintShim},\n"
  "  {\"codegen/decode/rle_block.cuh\", kEmbeddedJitHeaderRleBlock},\n"
  "};\n"
  "inline constexpr int kEmbeddedJitHeaderCount = 2;\n"
  "}  // namespace codegen::jit\n")
