# Generate a header that embeds the project headers the runtime NVRTC JIT
# #includes, as raw-string literals, so a binary distribution needs no simpatico
# source tree on disk. Invoked via `cmake -P` from an add_custom_command.
#
# Inputs (passed with -D): IN_STDINT  path to src/codegen/stdint_shim.hpp IN_RLE
# path to src/codegen/decode/rle_block.cuh OUT        path of the header to
# generate
#
# The embedded contents are handed to nvrtcCreateProgram() as named in-memory
# headers, so the include NAMES below must match the `#include "..."` strings
# used by the rendered kernel sources exactly.

include("${CMAKE_CURRENT_LIST_DIR}/jit_header_manifest.cmake")
file(READ "${IN_STDINT}" STDINT_SRC)
file(READ "${IN_RLE}" RLE_SRC)
jit_normalize_header("${STDINT_SRC}" STDINT_SRC)
jit_normalize_header("${RLE_SRC}" RLE_SRC)
jit_manifest_record("codegen/decode/rle_block.cuh" "${RLE_SRC}" rle_record)
jit_manifest_record("codegen/stdint_shim.hpp" "${STDINT_SRC}" stdint_record)
string(SHA256 manifest_digest
              "simpatico-headers-v1\n${rle_record}${stdint_record}")

# Raw-string delimiter chosen so it cannot appear in the embedded C++ source.
set(D "SIMPATICO_EMBED")

file(
  WRITE "${OUT}"
  "// AUTO-GENERATED by embed_jit_headers.cmake -- DO NOT EDIT.\n"
  "// Project headers the runtime NVRTC JIT #includes, embedded as in-memory\n"
  "// headers so a binary distribution needs no simpatico source tree on disk.\n"
  "#pragma once\n"
  "#include \"codegen/jit/embedded_header.h\"\n"
  "namespace codegen::jit {\n"
  "inline constexpr const char* kEmbeddedJitHeaderStdintShim =\n"
  "R\"${D}(${STDINT_SRC})${D}\";\n"
  "inline constexpr const char* kEmbeddedJitHeaderRleBlock =\n"
  "R\"${D}(${RLE_SRC})${D}\";\n"
  "// Names MUST match the `#include \"...\"` strings in the rendered kernels.\n"
  "inline constexpr EmbeddedJitHeader kEmbeddedJitHeaders[] = {\n"
  "  {\"codegen/stdint_shim.hpp\", kEmbeddedJitHeaderStdintShim},\n"
  "  {\"codegen/decode/rle_block.cuh\", kEmbeddedJitHeaderRleBlock},\n"
  "};\n"
  "inline constexpr int kEmbeddedJitHeaderCount = 2;\n"
  "inline constexpr char kEmbeddedJitHeadersIdentity[] = \"${manifest_digest}\";\n"
  "}  // namespace codegen::jit\n")
