# Derive the JIT cache epoch from the compiled objects of simpatico_jitgen: the
# NVRTC driver with its options and embedded headers (project and CCCL), and the
# cache-key encoding. Any change to the code that turns a cache key into a cubin
# changes these objects, so cubins cached by an older build are never looked up
# again. Code outside simpatico_jitgen (renderers, operators, plan, launchers,
# tests) cannot change the cubin for a given key: the key hashes the rendered
# source itself. Invoked via `cmake -P`.
#
# Required -D inputs: OBJECTS_FILE lists the object files, one per line; OUT is
# the .cpp to generate; STAMP is touched on every run. OUT is rewritten only
# when the epoch changes, so an unchanged epoch triggers no recompile/relink.
cmake_minimum_required(VERSION 3.24)

file(STRINGS "${OBJECTS_FILE}" objects)
list(LENGTH objects count)
if(count EQUAL 0)
  message(FATAL_ERROR "jit_epoch: no simpatico_jitgen objects listed")
endif()

# Hash the object contents only, never their paths, in the listed (source)
# order. The length prefix keeps the record boundaries unambiguous.
set(record "simpatico-jit-epoch-v1\n")
foreach(object IN LISTS objects)
  file(SHA256 "${object}" digest)
  string(APPEND record "64:${digest}")
endforeach()
string(SHA256 epoch "${record}")
# 128 bits are ample for telling builds apart and keep paths short.
string(SUBSTRING "${epoch}" 0 32 epoch)

string(
  CONCAT body
         "// AUTO-GENERATED by jit_epoch.cmake -- DO NOT EDIT.\n"
         "#include \"codegen/jit/jit_epoch.h\"\n"
         "namespace codegen::jit {\n"
         "const char kJitEpoch[] = \"${epoch}\";\n"
         "}  // namespace codegen::jit\n")

set(previous "")
if(EXISTS "${OUT}")
  file(READ "${OUT}" previous)
endif()
if(NOT previous STREQUAL body)
  file(WRITE "${OUT}" "${body}")
  message(STATUS "JIT cache epoch: ${epoch}")
endif()
file(TOUCH "${STAMP}")
