[package]
name = "doris-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
doris-thrift = { path = "../doris-thrift" }
doris-proto = { path = "../doris-proto" }
plan-translator = { path = "../plan-translator" }
result-formatter = { path = "../result-formatter" }
sirius-ffi = { path = "../sirius-ffi" }
thrift = "0.17"
tonic.workspace = true
prost.workspace = true
tokio.workspace = true
tracing.workspace = true
anyhow.workspace = true
thiserror.workspace = true
dashmap.workspace = true
arrow.workspace = true
substrait.workspace = true
