[package]
name = "sirius-telemetry-ui"
version.workspace = true
edition.workspace = true

[dependencies]
quent-analyzer = { git = "https://github.com/rapidsai/quent.git", rev = "ba843288dce6bea60a9cb3ed14111cc9c8828ef9", features = ["ts"] }
serde = { version = "1", features = ["derive"] }
ts-rs = { version = "11", features = ["uuid-impl", "serde-json-impl"] }
uuid = { version = "1", features = ["serde"] }
