[package]
name = "sirius-telemetry-instrumentation"
version.workspace = true
edition.workspace = true

[features]
collector = ["quent-instrumentation/io-collector"]

[dependencies]
quent-events = { git = "https://github.com/rapidsai/quent.git", rev = "53cb33a8eec9be623b60d236a01db4052f9bf260", features = ["serde"] }
quent-instrumentation = { git = "https://github.com/rapidsai/quent.git", rev = "53cb33a8eec9be623b60d236a01db4052f9bf260", features = ["io-msgpack", "io-ndjson", "io-postcard"] }
serde = { version = "1", features = ["derive"] }
uuid = { version = "1", features = ["serde", "v7"] }

[build-dependencies]
quent-build-info = { git = "https://github.com/rapidsai/quent.git", rev = "53cb33a8eec9be623b60d236a01db4052f9bf260" }
quent-instrumentation-build = { git = "https://github.com/rapidsai/quent.git", rev = "53cb33a8eec9be623b60d236a01db4052f9bf260" }
quent-yaml = { git = "https://github.com/rapidsai/quent.git", rev = "53cb33a8eec9be623b60d236a01db4052f9bf260" }
