set(DUCKDB_EXTENSION_CONFIGS
    "${CMAKE_CURRENT_LIST_DIR}/../extension_config.cmake"
    CACHE STRING "")

set(CMAKE_EXPORT_COMPILE_COMMANDS
    ON
    CACHE BOOL "")

set(CMAKE_C_COMPILER
    "$ENV{CONDA_PREFIX}/bin/clang"
    CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER
    "$ENV{CONDA_PREFIX}/bin/clang++"
    CACHE FILEPATH "")
set(CMAKE_CUDA_HOST_COMPILER
    "$ENV{CONDA_PREFIX}/bin/clang++"
    CACHE FILEPATH "")

set(CMAKE_C_COMPILER_LAUNCHER
    "sccache"
    CACHE STRING "")
set(CMAKE_CXX_COMPILER_LAUNCHER
    "sccache"
    CACHE STRING "")
set(CMAKE_CUDA_COMPILER_LAUNCHER
    "sccache"
    CACHE STRING "")

set(BUILD_TESTS
    ON
    CACHE BOOL "")
