include(${CMAKE_CURRENT_LIST_DIR}/common.cmake)

set(CMAKE_BUILD_TYPE Debug CACHE STRING "")

set(CMAKE_C_FLAGS_DEBUG "-g -O0" CACHE STRING "")
set(CMAKE_CXX_FLAGS_DEBUG "-g -O0" CACHE STRING "")
set(CMAKE_CUDA_FLAGS_DEBUG "-g -G -O0" CACHE STRING "")
