include(CMakeFindDependencyMacro)
find_dependency(CUDAToolkit)
find_dependency(Threads)
find_dependency(cudf CONFIG)
find_dependency(cuvs CONFIG)
find_dependency(raft CONFIG)
find_dependency(cuco CONFIG)
find_dependency(rmm CONFIG)
find_dependency(spdlog CONFIG)
find_dependency(yaml-cpp CONFIG)
find_dependency(roaring CONFIG)
find_dependency(OpenSSL)
find_dependency(absl CONFIG)
find_dependency(kvikio CONFIG)
find_dependency(nvcomp CONFIG)
find_dependency(nvrtc CONFIG)
find_dependency(nvjitlink CONFIG)
foreach(target CUDA::cusparse CUDA::cusparse_static)
  if(TARGET ${target})
    get_target_property(cusparse_links ${target} INTERFACE_LINK_LIBRARIES)
    if(cusparse_links)
      list(TRANSFORM cusparse_links REPLACE "^CUDA::nvJitLink(_static)?$"
                                            "nvjitlink::nvjitlink_static")
      set_target_properties(${target} PROPERTIES INTERFACE_LINK_LIBRARIES
                                                 "${cusparse_links}")
    endif()
  endif()
endforeach()
find_dependency(CURL CONFIG)
find_dependency(PkgConfig)
pkg_check_modules(NUMA REQUIRED IMPORTED_TARGET numa)
pkg_check_modules(LIBURING REQUIRED IMPORTED_TARGET liburing)
if(NOT TARGET Numa::Numa)
  add_library(Numa::Numa ALIAS PkgConfig::NUMA)
endif()
if(NOT TARGET cuvs::cuvs)
  add_library(cuvs::cuvs ALIAS cuvs::cuvs_static)
endif()
