/*
 * SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Vendored from cuCascade (b4abc2d:include/memory/host_table_packed.hpp) when cuCascade
// dropped its libcudf dependency (NVIDIA/cuCascade#142). cudf::pack-backed allocation, now owned by
// Sirius under namespace sirius::memory.

#pragma once

#include <cucascade/memory/fixed_size_host_memory_resource.hpp>

#include <cstdint>
#include <memory>
#include <vector>

namespace sirius {
namespace memory {

using cucascade::memory::fixed_multiple_blocks_allocation;

/**
 * @brief Structure containing both the host memory allocation and metadata for table recreation.
 *
 * This structure contains the actual memory allocation and the metadata required to recreate the
 * table. The metadata is a vector of uint8_t that contains the metadata for the table. The
 * data_size is the size of the data in the allocation.
 */
struct host_table_packed_allocation {
  /// Fixed-size buffers containing the table data
  fixed_multiple_blocks_allocation allocation;
  /// Metadata generated by cudf::pack, required for table reconstruction
  std::unique_ptr<std::vector<uint8_t>> metadata;
  /// Number of bytes stored in the allocation
  std::size_t data_size;

  host_table_packed_allocation(fixed_multiple_blocks_allocation alloc,
                               std::unique_ptr<std::vector<uint8_t>> meta,
                               std::size_t data_sz)
    : allocation(std::move(alloc)), metadata(std::move(meta)), data_size(data_sz)
  {
  }
};

}  // namespace memory
}  // namespace sirius
